# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 258e88bbeb9ba6df85cae4f421b273cb7b14e1165a235a11af09deccd8de7bee7141fe00d2c062c8b4950390347fe6b243113f1691b38466523528c42c2a22a8

test:
  secret_key_base: 5fb042ec81b54b00d40198b3830205ba3ce4406a0c9da6f0b1983fedbedd8e874dee29d6398c1d47458da9c4f7d21eafe3937accc847aa52f6302c6ab9773427

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
